import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../../utils/trpc";
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import NavBar from "../../components/NavBar";
import { useRouter } from "next/router";
import { useEffect, useRef, useState } from "react";
import GameCover from "../../components/GameCover";
import { UserSelect } from "../../components/UserSelect";
import { DeleteButton } from "../../components/DeleteButton";
import { LeaveButton } from "../../components/LeaveButton";

const GroupPage: NextPage = () => {
	const { data: session } = useSession();
	let steamId: string = "";
	if (session) {
		steamId = session?.steamId as string;
	}
	const router = useRouter();
	const [enabledUsers, setEnabledUsers] = useState<string[]>([]);
	const { groupId } = router.query as { groupId: string };

	const groupQuery = trpc.useQuery(["groups.getGroup", { groupId }]);
	const group = groupQuery.data;
	const groupMembersQuery = trpc.useQuery(["groups.getMembers", { groupId }]);
	const deleteGroup = trpc.useMutation(["groups.deleteGroup"]);
	const leaveGroup = trpc.useMutation(["groups.leaveGroup"]);
	const usersInstalledGamesQuery = trpc.useQuery(["library.getUsersInstalledGames", { steamIds: enabledUsers }]);
	const groupMembers = groupMembersQuery.data;
	const [disabledUsers, setDisabledUsers] = useState<string[]>([]);
	const [copyText, setCopyText] = useState("Click to copy!");
	// set disabledUsers to groupMembersSteamIds on first page load
	useEffect(() => {
		const groupMembersSteamIds: string[] = groupMembers?.map((member) => member?.steamId) as string[];

		setDisabledUsers(groupMembersSteamIds);
	}, [groupMembers]);

	async function copyTextToClipboard(text: string) {
		setCopyText("Copied!");
		if ("clipboard" in navigator) {
			return await navigator.clipboard.writeText(text);
		} else {
			return document.execCommand("copy", true, text);
		}
	}
	if (!groupId || typeof groupId !== "string") {
		return <div>Invalid Group Page</div>;
	}
	if (!groupQuery.data) {
		// TODO add error page
		return <div>Invalid Group Page</div>;
	}
	// check if user is in group
	const isMember = groupMembers?.some((member) => member?.userId === session?.user?.id);
	if (!isMember) {
		return <div>You are not a member of this group.</div>;
	}

	if (group && groupMembers && disabledUsers && enabledUsers) {
		const { ownerId, name, joinCode, id: groupId } = group;

		const isOwner = ownerId === session?.user?.id;
		console.log(group);
		console.log(groupMembers);

		return (
			<>
				<Head>
					<title>Groups</title>
					<meta name="description" content="Generated by create-t3-app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<NavBar></NavBar>

				<main className="container mx-auto flex flex-col items-center justify-center p-4">
					<div className="grid grid-cols-3 gap-10 items-center w-full mb-10">
						<div className="flex justify-start items-start">
							<button
								className="p-3 bg-violet-500 rounded"
								onClick={() => {
									// TODO write need help thing
									alert("I'm working on writing this!");
								}}
							>
								Need Help?
							</button>
						</div>
						<div className="flex flex-col justify-start items-center">
							<h1 className="text-7xl mb-5 px-5 pb-3 border-violet-500 border-b-4">{group.name}</h1>
							<p
								className="text-2xl cursor-pointer"
								onClick={() => {
									copyTextToClipboard(joinCode);
								}}
							>
								Join Code: {group.joinCode}
							</p>
							<p
								className="text-gray-500 cursor-pointer"
								onClick={() => {
									copyTextToClipboard(joinCode);
								}}
							>
								{copyText}
							</p>
						</div>
						<div className="flex justify-end items-end">
							<button
								className="p-3 bg-violet-500 rounded mr-5"
								onClick={() => {
									// TODO group settings
									alert("Editing group settings will come soon!");
								}}
							>
								Group Settings
							</button>
							{isOwner && groupMembers ? (
								<DeleteButton
									groupId={groupId}
									session={session}
									router={router}
									deleteGroup={deleteGroup}
									length={groupMembers.length}
								></DeleteButton>
							) : (
								<LeaveButton
									groupId={groupId}
									session={session}
									push={router.push}
									ownerId={group.ownerId}
									mutate={leaveGroup.mutate}
								></LeaveButton>
							)}
						</div>
					</div>

					<UserSelect
						enabledUsers={enabledUsers}
						setEnabledUsers={setEnabledUsers}
						usersInstalledGamesQuery={usersInstalledGamesQuery}
						groupMembers={groupMembers}
						disabledUsers={disabledUsers}
						setDisabledUsers={setDisabledUsers}
					></UserSelect>

					<h1 className="text-5xl border-violet-500 border-b-4 pb-3 px-5 my-20">Games You Can Play</h1>
					{usersInstalledGamesQuery.data?.length === 0 ? (
						<div className="text-2xl">
							{enabledUsers.length === 0
								? "Click on the user icons above to mark users as online and check what games they can all play!"
								: "Sorry, you guys don't have any games in common apparently!"}
						</div>
					) : (
						<div id="games" className="grid items-center grid-cols-5 gap-10 w-full">
							{usersInstalledGamesQuery.data?.map((appId: string) => {
								return (
									<GameCover
										appId={appId}
										installed={true}
										key={appId}
										alt={appId + " Game Cover"}
									></GameCover>
								);
							})}
						</div>
					)}
				</main>
			</>
		);
	}

	return <div>Loading</div>;
};

export async function getServerSideProps(context: any) {
	const session = await getSession(context);
	// TODO potentially. if you are trying to view a group that you don't belong to, you should be redirected to the groups page.
	// or if the group doesn't exist, you should be redirected to the groups page.
	// not sure if it should notify before redirect or just redirect
	// also not sure how to do it
	if (!session) {
		return {
			redirect: {
				destination: "/",
				permanent: false,
			},
		};
	}
	return {
		props: {
			session,
		},
	};
}

export default GroupPage;
