import type { NextPage } from "next";
import Head from "next/head";
import NavBar from "../components/NavBar";

const About: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App - Documentation</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar></NavBar>
			<main className="container mx-auto flex flex-col items-center justify-center p-4">
				<h1 className="text-center text-7xl mb-5 px-5 pb-5 font-bold border-violet-500 border-b-4">About</h1>
				<p className="text-center text-4xl w-3/4">All the info about this website!</p>
				<div className="flex flex-row">
					<div className="flex flex-col w-1/2 p-10">
						<h2 className="mb-3 text-center text-4xl">Who made this?</h2>
						<p>
							My name is Matthew, and I am an avid gamer and programmer. I mainly play Overwatch, but also
							mess around in other games like CS:GO, League of Legends and more. My main programming
							language is TypeScript/JavaScript. I am very interested in web design and enjoy creating
							beneficial things for others. I currently attend Purdue University, majoring in Computer
							Science. If you&apos;re curious to check out my other work, check out my GitHub page{" "}
							<a className="text-violet-500 underline" href="https://github.com/MonsteRico">
								here
							</a>
							. I&apos;m currently working on my portfolio website, and will link it as soon as it&apos;s
							ready. That&apos;s about it! Thanks for checking out the site! Enjoy! :){" "}
						</p>
					</div>
					<div className="w-1/2 bg-red-500"></div>
				</div>
				<div className="flex flex-row">
					<div className="w-1/2 bg-red-500"></div>

					<div className="flex flex-col w-1/2 p-10">
						<h2 className="mb-3 text-center text-4xl">Why did you make this?</h2>
						<p>
							There is an age old question that plagues friend groups everywhere: &quot;What should we
							play today?&quot;. This question often prompts the follow up question of &quot;Well what
							games can we all play?&quot;. People then proceed to spend 10-15 minutes looking through
							their Steam library or at other games that they own just to find something they all have in
							common. This issue has plagued my friend group for years. This website is meant to solve
							that issue, and make that process much easier. Instead of having to look through Steam or
							your game library, you can just go to this website and see what games you can play with your
							friends. Easy as that.
						</p>
						<br></br>
						<p>
							The other reason I made this was to take the skills I have learned and apply them to a real
							world project. I have been learning web development as a hobby for many years now, and I
							enjoy doing it. I have made many small projects, but I have never made anything that I would
							consider to be &quot;real&quot;. I have always wanted to make a website that other people
							would really have a use for, and this is the first one that I have made that fits that
							description. I hope you enjoy it!
						</p>
					</div>
				</div>
				<div className="flex flex-row">
					<div className="flex flex-col w-1/2 p-10">
						<h2 className="mb-3 text-center text-4xl">How did you make this?</h2>
						<p>
							In my previous experiences with web development, I have often avoided using frameworks like
							React or Next.js. Recently, I started getting more into them and decided to give them a try.
							This project uses something called the T3 stack, which is made up of TailwindCSS,
							TypeScript, tRPC, and Next.js. I have never used any of these technologies before, just
							React which is a part of the Next.js framework. Even though this was my first time using
							these things, I found them to be very easy to use and understand. If you are curious as to
							how I made this website, you can check out the source code{" "}
							<a
								className="text-violet-500 underline"
								href="https://github.com/MonsteRico/WhatGamesCanWePlay"
							>
								here
							</a>
						</p>
					</div>
					<div className="w-1/2 bg-red-500"></div>
				</div>
			</main>
		</>
	);
};

export default About;
