import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut } from "next-auth/react";
const Home: NextPage = () => {
	const { data: session } = useSession();
	let text: string = "Hello World";
	let steamId: string = "";
	if (session) {
		text = session?.user?.name as string;
		steamId = session?.steamId as string;
	}
	const hello = trpc.useQuery(["example.hello", { text }]);
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
				{session ? (
					<>
						<h1>Signed in as {session.user?.name}</h1>
						<div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
							{hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
						</div>
						{steamId ? (
							<div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
								<p>Your steamId {steamId}</p>
							</div>
						) : (
							<div>
								<p>
									You do not have a linked Steam id. Please link a Steam account with your Discord
									account in order to continue using this website.
								</p>
								{
									// TODO
									// optionally have an option to link a steam account manually
									// also can link to the link steam account page
								}
							</div>
						)}
						<button onClick={() => signOut()}>Sign Out</button>
					</>
				) : (
					<>
						<h1 className="text-5xl">Sign in</h1>
						<div className="pt-6 text-2xl text-blue-500 flex justify-center items-center w-full">
							{hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
						</div>
						<button className="p-3 mt-7 bg-blue-400  text-white rounded" onClick={() => signIn("discord")}>
							Sign in with Discord
						</button>
					</>
				)}
			</main>
		</>
	);
};

export default Home;
