import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import NavBar from "../components/NavBar";
import { OwnedGame } from "type-steamapi";
import Image from "next/future/image";
import GameCover from "../components/GameCover";
const Groups: NextPage = () => {
	const { data: session } = useSession();
	let text: string = "Hello World";
	let steamId: string = "";

	if (session) {
		text = session?.user?.name as string;
		steamId = session?.steamId as string;
	}

	const games = trpc.useQuery(["library.getGames", { steamId }]);
	// const game = trpc.useQuery(["library.getGame", { appId: "218620" }]);
	// console.log(game.data);
	// console.log(games.data);
	return (
		<>
			<Head>
				<title>My Library</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar></NavBar>

			<main className="container mx-auto flex flex-col justify-center items-center min-h-screen p-4">
				{steamId ? (
					<>
						<p className="pt-6 text-2xl text-blue-500 w-full">Your steamId {steamId}</p>
						<div id="games" className="grid grid-cols-3 gap-10 w-full">
							{games.data?.map((game: OwnedGame) => (
								<div key={game.appId} className="text-xl content-center self-center text-center">
									<GameCover appId={game.appId} alt={game.name} width={300} height={450}></GameCover>
									<p>{game.name}</p>
								</div>
							))}
						</div>
					</>
				) : (
					<div>
						<p>You do not have a linked Steam id.</p>
						{
							// TODO
							// optionally have an option to link a steam account manually
							// also can link to the link steam account page
						}
					</div>
				)}
			</main>
		</>
	);
};

export async function getServerSideProps(context: any) {
	const session = await getSession(context);
	if (!session) {
		return {
			redirect: {
				destination: "/",
				permanent: false,
			},
		};
	}
	return {
		props: {
			session,
		},
	};
}

export default Groups;
