import type { NextPage } from "next";
import Head from "next/head";
import CoolButton from "../components/CoolButton";
import NavBar from "../components/NavBar";

type TechnologyCardProps = {
	name: string;
	description: string;
	documentation: string;
};

const Documentation: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App - Documentation</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavBar></NavBar>
			<main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
				<h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold">Find a bug?</h1>
				<p>
					Bugs can be submitted to the public GitHub Repository (button below)! You can also DM Monster#8681
					on Discord. Let me know of any bugs you find, anything you think is hard to understand or not
					intuitive, any design things that should change whatever. All feedback is appreciated. Thank you!
				</p>
				<CoolButton
					onClick={() => {
						window.open("https://github.com/MonsteRico/WhatGamesCanWePlay/");
					}}
				>
					GitHub Link
				</CoolButton>
			</main>
		</>
	);
};

export default Documentation;
